// Generated by: npx supabase gen types typescript --local > types/database.ts
// Run this after any schema migration

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string;
          username: string | null;
          avatar_url: string | null;
          email: string;
          phone: string | null;
          state: string | null;
          contact_info_public: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          username?: string | null;
          avatar_url?: string | null;
          email: string;
          phone?: string | null;
          state?: string | null;
          contact_info_public?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string;
          username?: string | null;
          avatar_url?: string | null;
          email?: string;
          phone?: string | null;
          state?: string | null;
          contact_info_public?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      notification_preferences: {
        Row: {
          id: string;
          user_id: string;
          notification_type: string;
          enabled: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          notification_type: string;
          enabled?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          notification_type?: string;
          enabled?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notification_preferences_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      groups: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          cover_image_url: string | null;
          group_type:
            | "book_club"
            | "craft_night"
            | "supper_club"
            | "garden_club"
            | "game_night"
            | "custom";
          invite_code: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          cover_image_url?: string | null;
          group_type?:
            | "book_club"
            | "craft_night"
            | "supper_club"
            | "garden_club"
            | "game_night"
            | "custom";
          invite_code: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          cover_image_url?: string | null;
          group_type?:
            | "book_club"
            | "craft_night"
            | "supper_club"
            | "garden_club"
            | "game_night"
            | "custom";
          invite_code?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "groups_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      group_members: {
        Row: {
          id: string;
          group_id: string;
          user_id: string;
          role: "admin" | "member";
          joined_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          user_id: string;
          role?: "admin" | "member";
          joined_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          user_id?: string;
          role?: "admin" | "member";
          joined_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "group_members_group_id_fkey";
            columns: ["group_id"];
            isOneToOne: false;
            referencedRelation: "groups";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "group_members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      topics: {
        Row: {
          id: string;
          group_id: string;
          title: string;
          description: string | null;
          cover_url: string | null;
          status: "backlog" | "nominated" | "current" | "completed";
          author: string | null;
          page_count: number | null;
          external_id: string | null;
          nominated_by: string | null;
          nominated_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          group_id: string;
          title: string;
          description?: string | null;
          cover_url?: string | null;
          status?: "backlog" | "nominated" | "current" | "completed";
          author?: string | null;
          page_count?: number | null;
          external_id?: string | null;
          nominated_by?: string | null;
          nominated_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          group_id?: string;
          title?: string;
          description?: string | null;
          cover_url?: string | null;
          status?: "backlog" | "nominated" | "current" | "completed";
          author?: string | null;
          page_count?: number | null;
          external_id?: string | null;
          nominated_by?: string | null;
          nominated_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "topics_group_id_fkey";
            columns: ["group_id"];
            isOneToOne: false;
            referencedRelation: "groups";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "topics_nominated_by_fkey";
            columns: ["nominated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      topic_votes: {
        Row: {
          id: string;
          topic_id: string;
          user_id: string;
          voted_at: string;
        };
        Insert: {
          id?: string;
          topic_id: string;
          user_id: string;
          voted_at?: string;
        };
        Update: {
          id?: string;
          topic_id?: string;
          user_id?: string;
          voted_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "topic_votes_topic_id_fkey";
            columns: ["topic_id"];
            isOneToOne: false;
            referencedRelation: "topics";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "topic_votes_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      meetings: {
        Row: {
          id: string;
          group_id: string;
          topic_id: string | null;
          title: string | null;
          status: "draft" | "scheduling" | "confirmed" | "completed";
          location: string | null;
          virtual_link: string | null;
          host_id: string | null;
          scheduled_at: string | null;
          topic_poll_open: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          topic_id?: string | null;
          title?: string | null;
          status?: "draft" | "scheduling" | "confirmed" | "completed";
          location?: string | null;
          virtual_link?: string | null;
          host_id?: string | null;
          scheduled_at?: string | null;
          topic_poll_open?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          topic_id?: string | null;
          title?: string | null;
          status?: "draft" | "scheduling" | "confirmed" | "completed";
          location?: string | null;
          virtual_link?: string | null;
          host_id?: string | null;
          scheduled_at?: string | null;
          topic_poll_open?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "meetings_group_id_fkey";
            columns: ["group_id"];
            isOneToOne: false;
            referencedRelation: "groups";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "meetings_topic_id_fkey";
            columns: ["topic_id"];
            isOneToOne: false;
            referencedRelation: "topics";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "meetings_host_id_fkey";
            columns: ["host_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      availability_slots: {
        Row: {
          id: string;
          meeting_id: string;
          proposed_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          proposed_at: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          proposed_at?: string;
          created_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "availability_slots_meeting_id_fkey";
            columns: ["meeting_id"];
            isOneToOne: false;
            referencedRelation: "meetings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "availability_slots_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      availability_responses: {
        Row: {
          id: string;
          slot_id: string;
          user_id: string;
          response: "yes" | "no" | "maybe";
          responded_at: string;
        };
        Insert: {
          id?: string;
          slot_id: string;
          user_id: string;
          response: "yes" | "no" | "maybe";
          responded_at?: string;
        };
        Update: {
          id?: string;
          slot_id?: string;
          user_id?: string;
          response?: "yes" | "no" | "maybe";
          responded_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "availability_responses_slot_id_fkey";
            columns: ["slot_id"];
            isOneToOne: false;
            referencedRelation: "availability_slots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "availability_responses_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      rsvps: {
        Row: {
          id: string;
          meeting_id: string;
          user_id: string;
          response: "yes" | "no" | "maybe";
          note: string | null;
          responded_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          user_id: string;
          response: "yes" | "no" | "maybe";
          note?: string | null;
          responded_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          user_id?: string;
          response?: "yes" | "no" | "maybe";
          note?: string | null;
          responded_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "rsvps_meeting_id_fkey";
            columns: ["meeting_id"];
            isOneToOne: false;
            referencedRelation: "meetings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "rsvps_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      bring_list_items: {
        Row: {
          id: string;
          meeting_id: string;
          label: string;
          claimed_by: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          label: string;
          claimed_by?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          label?: string;
          claimed_by?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "bring_list_items_meeting_id_fkey";
            columns: ["meeting_id"];
            isOneToOne: false;
            referencedRelation: "meetings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "bring_list_items_claimed_by_fkey";
            columns: ["claimed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "bring_list_items_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      messages: {
        Row: {
          id: string;
          group_id: string;
          user_id: string;
          body: string;
          created_at: string;
          parent_id: string | null;
          image_url: string | null;
        };
        Insert: {
          id?: string;
          group_id: string;
          user_id: string;
          body: string;
          created_at?: string;
          parent_id?: string | null;
          image_url?: string | null;
        };
        Update: {
          id?: string;
          group_id?: string;
          user_id?: string;
          body?: string;
          created_at?: string;
          parent_id?: string | null;
          image_url?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "messages_group_id_fkey";
            columns: ["group_id"];
            isOneToOne: false;
            referencedRelation: "groups";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "messages";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_group_member: {
        Args: { gid: string };
        Returns: boolean;
      };
      is_group_admin: {
        Args: { gid: string };
        Returns: boolean;
      };
      lookup_group_by_invite_code: {
        Args: { code: string };
        Returns: Array<{
          id: string;
          name: string;
          group_type: string;
          description: string | null;
          cover_image_url: string | null;
          created_at: string;
        }>;
      };
    };
    Enums: Record<string, never>;
  };
};
