// Generated by: npx supabase gen types typescript --local > types/database.ts
// Run this after any schema migration

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string;
          avatar_url: string | null;
          email: string;
          created_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          avatar_url?: string | null;
          email: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string;
          avatar_url?: string | null;
          email?: string;
          created_at?: string;
        };
      };
      groups: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          cover_image_url: string | null;
          group_type:
            | "book_club"
            | "craft_night"
            | "supper_club"
            | "garden_club"
            | "game_night"
            | "custom";
          invite_code: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          cover_image_url?: string | null;
          group_type?:
            | "book_club"
            | "craft_night"
            | "supper_club"
            | "garden_club"
            | "game_night"
            | "custom";
          invite_code: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          cover_image_url?: string | null;
          group_type?:
            | "book_club"
            | "craft_night"
            | "supper_club"
            | "garden_club"
            | "game_night"
            | "custom";
          invite_code?: string;
          created_by?: string | null;
          created_at?: string;
        };
      };
      group_members: {
        Row: {
          id: string;
          group_id: string;
          user_id: string;
          role: "admin" | "member";
          joined_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          user_id: string;
          role?: "admin" | "member";
          joined_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          user_id?: string;
          role?: "admin" | "member";
          joined_at?: string;
        };
      };
      topics: {
        Row: {
          id: string;
          group_id: string;
          title: string;
          description: string | null;
          cover_url: string | null;
          status: "nominated" | "current" | "completed";
          author: string | null;
          page_count: number | null;
          external_id: string | null;
          nominated_by: string | null;
          nominated_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          group_id: string;
          title: string;
          description?: string | null;
          cover_url?: string | null;
          status?: "nominated" | "current" | "completed";
          author?: string | null;
          page_count?: number | null;
          external_id?: string | null;
          nominated_by?: string | null;
          nominated_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          group_id?: string;
          title?: string;
          description?: string | null;
          cover_url?: string | null;
          status?: "nominated" | "current" | "completed";
          author?: string | null;
          page_count?: number | null;
          external_id?: string | null;
          nominated_by?: string | null;
          nominated_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
      };
      topic_votes: {
        Row: {
          id: string;
          topic_id: string;
          user_id: string;
          voted_at: string;
        };
        Insert: {
          id?: string;
          topic_id: string;
          user_id: string;
          voted_at?: string;
        };
        Update: {
          id?: string;
          topic_id?: string;
          user_id?: string;
          voted_at?: string;
        };
      };
      meetings: {
        Row: {
          id: string;
          group_id: string;
          topic_id: string | null;
          title: string | null;
          status: "scheduling" | "confirmed" | "completed";
          location: string | null;
          virtual_link: string | null;
          host_id: string | null;
          scheduled_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          topic_id?: string | null;
          title?: string | null;
          status?: "scheduling" | "confirmed" | "completed";
          location?: string | null;
          virtual_link?: string | null;
          host_id?: string | null;
          scheduled_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          topic_id?: string | null;
          title?: string | null;
          status?: "scheduling" | "confirmed" | "completed";
          location?: string | null;
          virtual_link?: string | null;
          host_id?: string | null;
          scheduled_at?: string | null;
          created_at?: string;
        };
      };
      availability_slots: {
        Row: {
          id: string;
          meeting_id: string;
          proposed_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          proposed_at: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          proposed_at?: string;
          created_by?: string | null;
        };
      };
      availability_responses: {
        Row: {
          id: string;
          slot_id: string;
          user_id: string;
          response: "yes" | "no" | "maybe";
          responded_at: string;
        };
        Insert: {
          id?: string;
          slot_id: string;
          user_id: string;
          response: "yes" | "no" | "maybe";
          responded_at?: string;
        };
        Update: {
          id?: string;
          slot_id?: string;
          user_id?: string;
          response?: "yes" | "no" | "maybe";
          responded_at?: string;
        };
      };
      rsvps: {
        Row: {
          id: string;
          meeting_id: string;
          user_id: string;
          response: "yes" | "no" | "maybe";
          note: string | null;
          responded_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          user_id: string;
          response: "yes" | "no" | "maybe";
          note?: string | null;
          responded_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          user_id?: string;
          response?: "yes" | "no" | "maybe";
          note?: string | null;
          responded_at?: string;
        };
      };
      bring_list_items: {
        Row: {
          id: string;
          meeting_id: string;
          label: string;
          claimed_by: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          label: string;
          claimed_by?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          label?: string;
          claimed_by?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          group_id: string;
          user_id: string;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          user_id: string;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          user_id?: string;
          body?: string;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_group_member: {
        Args: { group_id: string };
        Returns: boolean;
      };
      is_group_admin: {
        Args: { group_id: string };
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
  };
};
